### ISSUE TITLE
Reaper 2.0

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#2412]
Motivation
----------
This issue is an overview ticket for the Reaper 2.0 re-design. All ideas/comments are collected in the [design proposal](https://docs.google.com/document/d/1EVP_UeSXU_IGsIZEZY3e_sb7CFvb9n71A8A_O6OkG1A/edit#).

# Re-Design work packages
- [x] Changes in heartbeat mode #2443  @bari12 
- [x] Outer loop: Preparation of the list of RSEs to delete on #2444 @cserf  
- [x] Inner loop: Actual storage interaction and deletion #2445 @tbeerman 
- [x] Documentation
- [x] Monitoring (Internal & External)

# Besides these general architecture changes, the overhaul should also address the following issues:
- [x] mode should be an RSE attribute #1804 
- [x] Protection of sources too strict in the reaper #1637

**Comment by cserf** [comment]
Done with my part. I also addressed the Protection of sources too strict
