### ISSUE TITLE
Documentation overhaul for the workshop

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#572]
This issue is used to track the changes and todos necessary for the general documentation overhaul for the workshop.

# General tasks
## General information
- [x] Concepts and Terminology (#566, @bari12)
- [x] Architecture (@bari12) - Depending on how much needs to be done, some help might be needed here

## Developer documentation
- [x] Contributer guide (from github) - should be only one line in the TOC (@vingar)
- [x] Installing dev environment (@vingar) - Docker example written by @berghaus can be used here.
- [x] REST API description (@tbeerman) - Some general information, some examples, rest auto generated
- [x] API description auto-generated (@vingar)
- [x] CLI description auto-generated (@vingar @cserf) for rucio, rucio-admin utilities and daemons

## User documentation
- [x] Installing Rucio clients (@cserf) - Mostly already there, only docker part needs to be added
- [x] Rucio Clients howto (#551, @cserf, @TomasJavurek) - Should be a generalized version of the ATLAS RuucioHowTo
- [x] Demo section based on docker and different steps (#696 @tbeerman, @cserf) - Basically installing a server, daemons etc in docker and then doing some things in this env

## Operator documentation
- [x] General information (@mlassnig) - Different ways of deploying rucio. Dependencies (DB, Transfertool, Messaging, Monitoring)
- [ ] Docker deployment
- [x] How to configure Rucio: rses, accounts, etc (#736,  @cserf)
- [x] How to version the DB with alembic, upgrade and downgrade instructions (@mlassnig)
- [ ] (Puppet deployment)
- [ ] (Kubernetes deployment)

# Bits & Pieces
- [x] Concepts needs to be expanded with information how a replica actually works on storage, with a dataset as example; how deterministic/non deterministic works; how scopes come into play etc. (@bari12)
- [x] How to connect and configure a stroage element to Rucio (@cserf)
- [ ] We also need something about dumps and ACLs in the op documentation
- [ ] How consistency and recovery can be done
- [x] List of return codes of bin/rucio (@mlassnig)
